### ISSUE TITLE
Setup warning : WebDAV interface seems to be broke

### ISSUE THREAD

**Issue by rperezb** [owncloud-archive/acceptance-testing#21]
Being connected to acceptance-testing:
INFO: git[/usr/local/src/owncloud-core] checked out branch: master reference: d426a09f900c2edcbe03ee63d1a9f819303de240

By connecting to admin account and access to: "Admin" screen, the following warning is shown: 

Setup Warning
Your web server is not yet properly setup to allow files synchronization because the WebDAV interface seems to be broken.    Please double check the installation guides.

Web browser:

Firefox and Chrome

**Comment by DeepDiver1975** [comment]
thx

**Comment by DeepDiver1975** [comment]
@jakobsack any time for some litmus testing the vm configuration? Just asking ... THX

**Comment by jakobsack** [comment]
@rperezb which vm are you using? master_on_apache_with_sqlite?

**Comment by rperezb** [comment]
Yes, master_on_apache_with_sqlite

**Comment by DeepDiver1975** [comment]
the apache config is wrong.
htaccess is not evaluated due to `AllowOverride None`

**Comment by DeepDiver1975** [comment]
fixed with #22

**Comment by DeepDiver1975** [comment]
@rperezb please pull latest version from this repo

**Comment by rperezb** [comment]
@DeepDiver1975 I still have this alert:

"Your web server is not yet properly setup to allow files synchronization because the WebDAV interface seems to be broken.   Please double check the installation guides."

By looking at the Log:

Debug   core    include path for class "OC_Share_Backend_File" starts with "apps/"  February 21, 2013 12:14

**Comment by rperezb** [comment]
It does work, THX

**Comment by alexisju** [comment]
I still have this message using the web-installer. 
I'm sorry but it still an issue. After an automatic installation, have this kind of message who refer to the manual installation (http://doc.owncloud.org/server/5.0/admin_manual/installation.html) in not helpfull for non-developer users.

Moreover, the alert don't give enough information to understand what is the trouble.

OC5.0.0 "stable" release
